spring:
  application:
    name: SGLiaStudio

  datasource:
    url: jdbc:mysql://localhost:3306/liastudio
    username: LiaStudio
    password: liaStudio12


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  security:
    user:
      name: liaStudio
      password: liaStudio12

server:
  port: 8081
